

#################### Spring Cloud Stream ####################
spring:
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      function:
        definition: streamConsumer;
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        streamSend-out-0:
          destination: stream_send  # topic 往主题发送
        streamConsumer-in-0:
          destination: stream_send  # topic 被下面消费者组订阅
          group: stream_send_consumer_group
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        default: # 默认 bindings 全局配置
          producer: # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            group: stream_producer_group # 生产者分组
            send-type: SYNC # 发送模式，SYNC 同步

        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: 47.99.163.33:9876 # RocketMQ Namesrv 地址



#################### Spring Cloud Bus 配置文件需要配合 Stream使用 好鸡肋 ... ####################

#spring:
#  cloud:
    # Spring Cloud Bus 配置项，对应 BusProperties 类
    bus:
      enabled: true # 是否开启，默认为 true
      id: ${spring.application.name}:${server.port} # 编号，Spring Cloud Alibaba 建议使用“应用:端口”的格式
      destination: springCloudBus # 目标消息队列，默认为 springCloudBus  创建了主题却没有消费者来消费 无语....



