server:
  port: 8888
  servlet:
    session:
      timeout: 10

spring:
  application:
    name: java-base

  profiles:
    active: mq


# spring-doc-openapi项目配置
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.ww.springcloud

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    enable-footer: false


#mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/frame-demo?useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout: 10000
#      idle-timeout: 30000
#      max-lifetime: 900000
#    type: com.zaxxer.hikari.HikariDataSource

  #纯粹多数据源
#  datasource:
#    dynamic:
#      primary: teacher #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        teacher:
#          url: jdbc:mysql://localhost:3306/frame-demo?useSSL=false
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          hikari:
#            connection-test-query: SELECT 1
#            connection-timeout: 10000
#            idle-timeout: 30000
#            max-lifetime: 900000
#          type: com.zaxxer.hikari.HikariDataSource
#        student:
#          url: jdbc:mysql://192.16.28.219:3306/test?useSSL=false
#          username: root
#          password: sne4mysql
#          driver-class-name: com.mysql.jdbc.Driver
#          hikari:
#            connection-test-query: SELECT 1
#            connection-timeout: 10000
#            idle-timeout: 30000
#            max-lifetime: 900000
#          type: com.zaxxer.hikari.HikariDataSource

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#  type-aliases-package: com.ww

logging:
  level:
    com.ww: debug
  pattern:
    dateformat: HH:mm:ss:SSS